### PR TITLE
logistic regression model, is implemented and working

### LINKED ISSUE #1: Remove Numpy Code
There is a lot of code written purely in Numpy convert that code to use Pytorch

### PR DESCRIPTION
**Pull request by govindansriram**
Added the Logistic Regression Model, and deleted all numpy base files

### CODE REVIEW

**Comment by govindansriram** [comment]
Having a few issues with multi class recommendations I've seen that online people just increase neuron size I might just go with that option for non binary classification. I just need to justify it with the math.

**Comment by govindansriram** [comment]
I believe the Multi Class Logistic Regression Model is working I tested it out it seems to be doing real good, the binary classifier also does really well on the breast cancer dataset. Now all I need to test is all these models on the MNIST dataset. Hopefully it goes well.

**Comment by govindansriram** [comment]
I tested it on the MNIST Dataset got 92% accuracy on the multi class model! 
logisticRegressionAccuracy

**Comment by govindansriram** [comment]
BinaryLogisticRegressionAccuracy
99% baby

**Review by sanumalav — APPROVED** [review]
Everything looks good man! The multiClassLogisticMethod seems pretty cool to do. I do think a comment (like a sentence) on what each method does is helpful for the reader though just in case.

**Pull request merged**
